# Generated by Django 5.2.14 on 2026-05-25 07:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('csv', 'CSV Upload'), ('sftp', 'SFTP'), ('manual', 'Manual Entry'), ('integration', 'Integration')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('retired', 'Retired')], db_index=True, default='active', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('tenant', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='emissions_t_status_627070_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('ingestion_batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=128)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('normalized', 'Normalized'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='received', max_length=20)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='emissions.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.tenant')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('activity_type', models.CharField(blank=True, max_length=120)),
                ('activity_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activity_unit', models.CharField(choices=[('kg_co2e', 'kg CO2e'), ('t_co2e', 't CO2e'), ('kwh', 'kWh'), ('mwh', 'MWh'), ('gj', 'GJ'), ('liter', 'Liter'), ('cubic_meter', 'Cubic meter'), ('km', 'Kilometer'), ('mile', 'Mile'), ('passenger_km', 'Passenger kilometer')], max_length=30)),
                ('normalized_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(choices=[('kg_co2e', 'kg CO2e'), ('t_co2e', 't CO2e'), ('kwh', 'kWh'), ('mwh', 'MWh'), ('gj', 'GJ'), ('liter', 'Liter'), ('cubic_meter', 'Cubic meter'), ('km', 'Kilometer'), ('mile', 'Mile'), ('passenger_km', 'Passenger kilometer')], default='kg_co2e', max_length=30)),
                ('co2e_kg', models.DecimalField(decimal_places=6, max_digits=20)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspicious_flags', models.JSONField(blank=True, default=list)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_emission_records', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.datasource')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.tenant')),
            ],
            options={
                'ordering': ('-period_start', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('ingest', 'Ingest'), ('lock', 'Lock')], db_index=True, max_length=30)),
                ('entity_type', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissions_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.tenant')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'processing_status'], name='emissions_r_tenant__a2708d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'data_source', 'received_at'], name='emissions_r_tenant__1d164b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'source_record_id'], name='emissions_r_tenant__34b024_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'data_source', 'payload_hash'), name='unique_raw_payload_per_source'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'period_start'], name='emissions_e_tenant__d14736_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'approval_status'], name='emissions_e_tenant__860cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'is_suspicious'], name='emissions_e_tenant__ce219a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'data_source', 'source_record_id'], name='emissions_e_tenant__0e5e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='emission_period_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('activity_value__gte', Decimal('0'))), name='emission_activity_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_value__gte', Decimal('0'))), name='emission_normalized_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('co2e_kg__gte', Decimal('0'))), name='emission_co2e_kg_non_negative'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'source_type'], name='emissions_d_tenant__9a7301_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'status'], name='emissions_d_tenant__9edc12_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_data_source_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='emissions_a_tenant__435d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action', 'occurred_at'], name='emissions_a_tenant__0a7111_idx'),
        ),
    ]
